//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsportManager.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EsportManager.Resources.Strings.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tjek status.
        /// </summary>
        internal static string CheckStatus {
            get {
                return ResourceManager.GetString("CheckStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ryd kø.
        /// </summary>
        internal static string ClearQueue {
            get {
                return ResourceManager.GetString("ClearQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopiér Fortnite-spilfiler.
        /// </summary>
        internal static string CopyFortniteGameFiles {
            get {
                return ResourceManager.GetString("CopyFortniteGameFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopiér Fortnite-manifester.
        /// </summary>
        internal static string CopyFortniteManifests {
            get {
                return ResourceManager.GetString("CopyFortniteManifests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrumentbræt.
        /// </summary>
        internal static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enhed er null.
        /// </summary>
        internal static string DeviceIsNull {
            get {
                return ResourceManager.GetString("DeviceIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} er offline.
        /// </summary>
        internal static string DeviceIsOffline {
            get {
                return ResourceManager.GetString("DeviceIsOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} er online.
        /// </summary>
        internal static string DeviceIsOnline {
            get {
                return ResourceManager.GetString("DeviceIsOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enheder.
        /// </summary>
        internal static string Devices {
            get {
                return ResourceManager.GetString("Devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP-adresse.
        /// </summary>
        internal static string IpAddress {
            get {
                return ResourceManager.GetString("IpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAC-adresse.
        /// </summary>
        internal static string MacAddress {
            get {
                return ResourceManager.GetString("MacAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        internal static string Manager {
            get {
                return ResourceManager.GetString("Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navn.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ikke fundet.
        /// </summary>
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beklager, indholdet du leder efter, eksisterer ikke..
        /// </summary>
        internal static string NotFoundMessage {
            get {
                return ResourceManager.GetString("NotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output:.
        /// </summary>
        internal static string OutputLabel {
            get {
                return ResourceManager.GetString("OutputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proces afsluttet med kode {0}.
        /// </summary>
        internal static string ProcessExitedWithCode {
            get {
                return ResourceManager.GetString("ProcessExitedWithCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proces startet; ID: {0}.
        /// </summary>
        internal static string ProcessStarted {
            get {
                return ResourceManager.GetString("ProcessStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nogle filer eller mapper kunne ikke kopieres (kopieringsfejl opstod og forsøgsgrænsen blev overskredet)..
        /// </summary>
        internal static string RobocopyCopyErrors {
            get {
                return ResourceManager.GetString("RobocopyCopyErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekstra filer eller mapper blev fundet. Filer eller mapper med uoverensstemmelser blev fundet..
        /// </summary>
        internal static string RobocopyExtraAndMismatch {
            get {
                return ResourceManager.GetString("RobocopyExtraAndMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekstra filer eller mapper blev fundet..
        /// </summary>
        internal static string RobocopyExtraFilesDetected {
            get {
                return ResourceManager.GetString("RobocopyExtraFilesDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alvorlig fejl. Robocopy kopierede ingen filer..
        /// </summary>
        internal static string RobocopyFatalError {
            get {
                return ResourceManager.GetString("RobocopyFatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En eller flere filer blev kopieret..
        /// </summary>
        internal static string RobocopyFilesCopied {
            get {
                return ResourceManager.GetString("RobocopyFilesCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En eller flere filer blev kopieret. Ekstra filer eller mapper blev fundet..
        /// </summary>
        internal static string RobocopyFilesCopiedAndExtra {
            get {
                return ResourceManager.GetString("RobocopyFilesCopiedAndExtra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En eller flere filer blev kopieret. Filer eller mapper med uoverensstemmelser blev fundet..
        /// </summary>
        internal static string RobocopyFilesCopiedAndMismatch {
            get {
                return ResourceManager.GetString("RobocopyFilesCopiedAndMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En eller flere filer blev kopieret. Ekstra filer eller mapper blev fundet. Filer eller mapper med uoverensstemmelser blev fundet..
        /// </summary>
        internal static string RobocopyFilesCopiedExtraAndMismatch {
            get {
                return ResourceManager.GetString("RobocopyFilesCopiedExtraAndMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filer eller mapper med uoverensstemmelser blev fundet..
        /// </summary>
        internal static string RobocopyMismatchDetected {
            get {
                return ResourceManager.GetString("RobocopyMismatchDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingen filer blev kopieret. Ingen fejl opstod. Ingen filer var forskellige..
        /// </summary>
        internal static string RobocopyNoFilesCopied {
            get {
                return ResourceManager.GetString("RobocopyNoFilesCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan netværk for enheder.
        /// </summary>
        internal static string ScanNetworkForDevices {
            get {
                return ResourceManager.GetString("ScanNetworkForDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Søg.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vis detaljer.
        /// </summary>
        internal static string ShowDetails {
            get {
                return ResourceManager.GetString("ShowDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start kø.
        /// </summary>
        internal static string StartQueue {
            get {
                return ResourceManager.GetString("StartQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annulleret af bruger.
        /// </summary>
        internal static string StatusCancelledByUser {
            get {
                return ResourceManager.GetString("StatusCancelledByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annulleret med fejl.
        /// </summary>
        internal static string StatusCancelledWithError {
            get {
                return ResourceManager.GetString("StatusCancelledWithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Færdig.
        /// </summary>
        internal static string StatusFinished {
            get {
                return ResourceManager.GetString("StatusFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Færdig med fejl.
        /// </summary>
        internal static string StatusFinishedWithError {
            get {
                return ResourceManager.GetString("StatusFinishedWithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialiseret.
        /// </summary>
        internal static string StatusInitialized {
            get {
                return ResourceManager.GetString("StatusInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        internal static string StatusLabel {
            get {
                return ResourceManager.GetString("StatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kører.
        /// </summary>
        internal static string StatusRunning {
            get {
                return ResourceManager.GetString("StatusRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop opdatering.
        /// </summary>
        internal static string StopUpdate {
            get {
                return ResourceManager.GetString("StopUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opgavekø.
        /// </summary>
        internal static string TaskQueue {
            get {
                return ResourceManager.GetString("TaskQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tænd.
        /// </summary>
        internal static string TurnOn {
            get {
                return ResourceManager.GetString("TurnOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tænd valgte enheder.
        /// </summary>
        internal static string TurnOnSelectedDevices {
            get {
                return ResourceManager.GetString("TurnOnSelectedDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opdater Fortnite.
        /// </summary>
        internal static string UpdateFortnite {
            get {
                return ResourceManager.GetString("UpdateFortnite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opdater Fortnite på valgte enheder.
        /// </summary>
        internal static string UpdateFortniteOnSelected {
            get {
                return ResourceManager.GetString("UpdateFortniteOnSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venter 30 sekunder på svar fra enhed.
        /// </summary>
        internal static string Waiting30Seconds {
            get {
                return ResourceManager.GetString("Waiting30Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venter 5 sekunder på svar fra enhed.
        /// </summary>
        internal static string Waiting5Seconds {
            get {
                return ResourceManager.GetString("Waiting5Seconds", resourceCulture);
            }
        }
    }
}
